spring:
  application:
    name: content-collection-service
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8083

qdrant:
  url: http://qdrant:6333
  collection: articles

management:
  endpoints:
    web:
      exposure:
        include: health, info